enum Purchase {
    SHOPPING_DATE = 'FECHA_COMPRA',
    CONCEPT = 'CONCEPTO',
    TOTAL_AMOUNT = 'IMPORTE_TOTAL',
    NUMBER_QUOTA = 'N_CUOTA',
    AMOUNT_QUOTA = 'MONTO_CUOTA',
    PAY_QUOTA_DATE = 'FECHA_PAGO_CUOTA',
    IS_PAY = 'SI' | 'NO'
}

enum Income {
    INCOME_DATE = 'FECHA_INGRESO',
    CONCEPT = 'CONCEPTO',
    TOTAL_AMOUNT = 'IMPORTE_TOTAL'
}
